config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'products#index'

  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
      end
  end

  resources :cart_items

  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end

  namespace :account do
    resources :orders
  end
end

app/models/order.rb
class Order < ApplicationRecord
    before_create :generate_token
    belongs_to :user
    has_many :product_lists
    validates :billing_name, presence: true
    validates :billing_address, presence: true
    validates :shipping_name, presence: true
    validates :shipping_address, presence: true

    def generate_token
        self.token = SecureRandom.uuid
    end

    def set_payment_with!(method)
        self.update_columns(payment_method: method )
    end
     
    def pay!
        self.update_columns(is_paid: true )
    end

    include AASM

  aasm do
    state :order_placed, initial: true
    state :paid
    state :shipping
    state :shipped
    state :order_cancelled
    state :good_returned


    event :make_payment, after_commit: :pay! do
      transitions from: :order_placed, to: :paid
    end

    event :ship do
      transitions from: :paid,         to: :shipping
    end

    event :deliver do
      transitions from: :shipping,     to: :shipped
    end

    event :return_good do
      transitions from: :shipped,      to: :good_returned
    end

    event :cancel_order do
      transitions from: [:order_placed, :paid], to: :order_cancelled
    end
  end
end

app/controllers/account/orders_controller.rb
class Account::OrdersController < ApplicationController
    before_action :authenticate_user!

    def index
        @orders = current_user.orders.order("id DESC")
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    layout "admin"

    before_action :authenticate_user!
    before_action :admin_required
    before_action :set_order , only: [:show, :ship, :shipped, :cancel, :return]
    def index
        @orders = Order.order("id DESC")
    end

    def show
        @product_lists = @order.product_lists
    end

    def ship
        @order.ship!
        OrderMailer.notify_ship(@order).deliver!
        redirect_to :back
    end
    
    def shipped
        @order.deliver!
        redirect_to :back
    end
    
    def cancel
        @order.cancel_order!
        OrderMailer.notify_cancel(@order).deliver!
        redirect_to :back
    end
    
    def return
        @order.return_good!
        redirect_to :back
    end

    private
    def set_order
        @order = Order.find(params[:id])
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :authenticate_user!, only: [:create]
    before_action :set_token , only: [:show, :pay_with_alipay, :pay_with_wechat, :apply_to_cancel]

    def create
      @order = Order.new(order_params)
      @order.user = current_user
      @order.total = current_cart.total_price
  
        if @order.save
            current_cart.cart_items.each do |cart_item|
            product_list = ProductList.new
            product_list.order = @order
            product_list.product_name = cart_item.product.title
            product_list.product_price = cart_item.product.price
            product_list.quantity = cart_item.quantity
            product_list.save
        end
        current_cart.clean!
        OrderMailer.notify_order_placed(@order).deliver!

        redirect_to order_path(@order.token)
      else
        render 'carts/checkout'
      end
    end
  
    def show
        @product_lists = @order.product_lists
    end

    def pay_with_alipay
        @order.set_payment_with!("alipay")
        @order.make_payment!
    
        redirect_to order_path(@order.token), notice: "使用支付宝成功完成付款"
    end
    
    def pay_with_wechat
        @order.set_payment_with!("wechat")
        @order.make_payment!
    
        redirect_to order_path(@order.token), notice: "使用微信成功完成付款"
    end

    def apply_to_cancel
        OrderMailer.apply_cancel(@order).deliver!
        flash[:notice] = "已提交申请"
        redirect_to :back
    end

    private
    def order_params
      params.require(:order).permit(:billing_name, :billing_address, :shipping_name, :shipping_address)
    end

    private
    def set_token
      @order = Order.find_by_token(params[:id])
    end
end

app/helpers/account/orders_helper.rb
module Account::OrdersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
    def render_order_paid_state(order)
        if order.is_paid?
          "已付款"
        else
          "未付款"
        end
    end
end

app/views/orders/show.html.erb
<div class="row">
    <div class="col-md-12">
        <h2>訂單明細</h2>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th width="80%">商品明細</th>
                    <th>單價</th>
                </tr>
            </thead>
            <tbody>
                <% @product_lists.each do |product_list| %>
                <tr>
                    <td>
                        <%= product_list.product_name %>
                    </td>
                    <td>
                        <%= product_list.product_price %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
        <div class="total clearfix">
            <span class="pull-right">
                總計<%= @order.total %>元
            </span>
        </div>
        <hr>
        <h2>寄送資訊</h2>
        <table class="table table-striped table-bordered">
            <tbody>
                <tr>
                    <th>
                        訂購人姓名
                    </th>
                    <th>
                        訂購人地址
                    </th>
                </tr>
                <tr>
                    <td>
                        <%= @order.billing_name %>
                    </td>
                    <td>
                        <%= @order.billing_address %>
                    </td>
                </tr>
                <tr>
                    <th>
                        收件人姓名
                    </th>
                    <th>
                        收件人地址
                    </th>
                </tr>
                <tr>
                    <td>
                        <%= @order.shipping_name %>
                    </td>
                    <td>
                        <%= @order.shipping_address %>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="pull-left">
            <% if @order.order_placed? || @order.paid? %>
            <%= link_to("申請取消訂單", apply_to_cancel_order_path(@order.token), method: :post, class: "btn  btn-info") %>
            <% end %>
        </div>
        <% if !@order.is_paid? %>
        <div class="group pull-right">
            <%= link_to("以支付寶付款", pay_with_alipay_order_path(@order.token), :method => :post, :class => "btn btn-danger") %>
            <%= link_to("以微信付款", pay_with_wechat_order_path(@order.token), :method => :post, :class => "btn btn-danger") %>
        </div>
        <% else %>
        <p class="text-center">此訂單已完成付款</p>
        <% end %>
    </div>
</div>